### ISSUE TITLE
Prueba 1

### ISSUE THREAD

**Issue by nbxandresvejar** [miguelovia/challenge-1#1]
Resultados: Miguel Villegas
Ciclo: 1

Problema 1: PHP
- El archivo de entrada se encuentra fijo por lo que no se le puede especificar otro nombre de archivo
- El formato de salida es un archivo el cual no se crea como se especifica
- Favor de ajustar estos dos issues para poder continuar con las pruebas.

Problema 2: PHP
- El archivo de entrada se encuentra fijo por lo que no se le puede especificar otro nombre de archivo
- El formato de salida es un archivo el cual no se crea como se especifica. Favor de generar la salida correcta.
- El entendimiento del problema es correcto, solo realizar los ajustes solicitados.

Problema 2: Python
- El archivo de entrada se encuentra fijo por lo que no se le puede especificar otro nombre de archivo. Favor de usar argumentos
- Se recomiendo el tratamiento de excepciones
- El entendimiento del problema es correcto, solo realizar los ajustes solicitados.

Por favor responde en este issue cuando estén resueltos. Saludos!

**Comment by miguelovia** [comment]
Se realizaron ajustes correspondientes.
