### ISSUE TITLE
Prueba 2

### ISSUE THREAD

**Issue by nbxandresvejar** [miguelovia/challenge-1#2]
Miguel puedes revisar los escenarios fallidos por fa, ya para completar el challenge. Saludos
Resultados: Miguel Villegas
Ciclo: 2

Problema 1: PHP
P1-CP1-EntradaEjemplo: Fail
P1-CP1-EntradaCorrecta: Pass
P1-CP2-LongitudLinea1Invalida: Pass
P1-CP3-LongitudLinea2Invalida: Pass
P1-CP4-LongitudMensajeInvalido: Fail
P1-CP5-LongitudMensajeMenor3: Pass
P1-CP6-LongitudMensajeMayor5000: Pass
P1-CP7-LongitudInstruccion1Menor2: Pass
P1-CP8-LongitudInstruccion2Menor2: Pass
P1-CP9-CaracteresInvalidosMensaje: Fail, no tiene el mensaje correcto
P1-CP10-LongitudInstruccion1Mayor50: Pass
P1-CP11-LongitudInstruccion2Mayor50: Pass
P1-CP12-DosInstruccionesEnMensaje: Fail
P1-CP13-InstruccionCaracterRepetido: Fail, Mismo escenario caso de ejemplo

Problema 2: PHP
P2-CP01-Ejemplo: Pass
P2-CP02-GanadorP2_R7_282: Pass
P2-CP03_GanadorP1_R6_102: Pass
P2-CP04-RondasMayoresAEntrada: Pass
P2-CP05-RondasMenoresAEntrada: Pass
P2-CP06-CaracteresEnNumeroRondas: Pass
P2-CP07-CaracteresEnValorRonda: Fail
P2-CP08-OK-Limite-10000: Pass
P2-CP09-DesbordeDeValoresRonda: Pass

Problema 2: Python
P2-CP01-Ejemplo: Pass
P2-CP02-GanadorP2_R7_282: Pass
P2-CP03_GanadorP1_R6_102: Pass
P2-CP04-RondasMayoresAEntrada: Pass
P2-CP05-RondasMenoresAEntrada: Pass
P2-CP06-CaracteresEnNumeroRondas: Pass
P2-CP07-CaracteresEnValorRonda: Pass
P2-CP08-OK-Limite-10000: Pass
P2-CP09-DesbordeDeValoresRonda: Pass

**Comment by miguelovia** [comment]
Nuevos ajustes realizados.
